# Задание
Есть мнение: раньше снимали настоящее кино, не то что сейчас.

Ваша задача — проверить это утверждение, используя файлы с рейтингами фильмов movies_stats.csv. То есть проверить, верно ли, что с ростом года выпуска фильма средний рейтинг становится ниже.

При этом мы не будем затрагивать субъективные факторы этих рейтингов, а пройдёмся по следующему алгоритму:

В переменную years запишите список из всех годов с 1950-го по 2010-й.

Напишите функцию production_year, которая каждой строке из названия фильма выставляет год выпуска (год выпуска берём из столбца title).

*** Не все названия фильмов содержат год выпуска в одинаковом формате, поэтому используйте следующий алгоритм:

- для каждой строки пройдите по всем годам списка years;
- если номер года присутствует в названии фильма, то функция возвращает этот год как год выпуска;
- если ни один из номеров года списка years не встретился в названии фильма, то возвращается 1900 год.

Запишите год выпуска фильма по алгоритму пункта 2 в новый столбец ‘year’.

Посчитайте средний рейтинг всех фильмов для каждого значения столбца ‘year’ и отсортируйте результат по убыванию рейтинга.

In [1]:
import pandas as pd

In [2]:
df_movies = pd.read_csv('C:\\Users\\User\\Desktop\\Аналитик данных\\ДЗ\\Итоговое ДЗ 9 Питон\\movies_stats.csv', sep=',', encoding='utf-8')

In [3]:
df_movies.head(5) #чтение файла с фильмами для проверки

,userId,movieId,rating,timestamp,title,genres
0,1,31,2.5,1260759144,Dangerous Minds (1995),Drama
1,1,1029,3.0,1260759179,Dumbo (1941),Animation|Children|Drama|Musical
2,1,1061,3.0,1260759182,Sleepers (1996),Thriller
3,1,1129,2.0,1260759185,Escape from New York (1981),Action|Adventure|Sci-Fi|Thriller
4,1,1172,4.0,1260759205,Cinema Paradiso (Nuovo cinema Paradiso) (1989),Drama

In [4]:
# В переменную years запишите список из всех годов с 1950-го по 2010-й
years = list(range(1950, 2011))

print(years) #проверка списка

[1950, 1951, 1952, 1953, 1954, 1955, 1956, 1957, 1958, 1959, 1960, 1961, 1962, 1963, 1964, 1965, 1966, 1967, 1968, 1969, 1970, 1971, 1972, 1973, 1974, 1975, 1976, 1977, 1978, 1979, 1980, 1981, 1982, 1983, 1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010]

In [5]:
#Напишите функцию production_year, которая каждой строке из названия фильма выставляет год выпуска (год выпуска берём из столбца title)

def production_year(film_year):
    for year in years:
        if str(year) in film_year:
            return int(year)
    return 1900

In [6]:
#применение функции к файлу и запись в новый столбец year

df_movies['year'] = df_movies['title'].apply(production_year)

#обращаю внимание, что по заданию список начинается с 1950 г., а в названиях фильмов, есть года ранее 1950, например Dumbo (1941)

df_movies.head(5)

,userId,movieId,rating,timestamp,title,genres,year
0,1,31,2.5,1260759144,Dangerous Minds (1995),Drama,1995
1,1,1029,3.0,1260759179,Dumbo (1941),Animation|Children|Drama|Musical,1900
2,1,1061,3.0,1260759182,Sleepers (1996),Thriller,1996
3,1,1129,2.0,1260759185,Escape from New York (1981),Action|Adventure|Sci-Fi|Thriller,1981
4,1,1172,4.0,1260759205,Cinema Paradiso (Nuovo cinema Paradiso) (1989),Drama,1989

In [7]:
#Посчитайте средний рейтинг всех фильмов для каждого значения столбца ‘year’.
# группирую по году и посчитаю средний рейтинг
df_movies_av_rating = df_movies.groupby('year').agg(
    av_rating=('rating', 'mean'),
).reset_index()

df_movies_av_rating.head

<bound method NDFrame.head of     year  av_rating
0   1900   3.602960
1   1950   3.915254
2   1951   3.983539
3   1952   4.000000
4   1953   3.754587
..   ...        ...
57  2006   3.511478
58  2007   3.548538
59  2008   3.498057
60  2009   3.520378
61  2010   3.537157

[62 rows x 2 columns]>

In [8]:
# сортировка результата по убыванию рейтинга
final = df_movies_av_rating.sort_values('av_rating', ascending=False)
final.head

<bound method NDFrame.head of     year  av_rating
8   1957   4.014241
23  1972   4.011136
3   1952   4.000000
5   1954   3.994220
2   1951   3.983539
..   ...        ...
56  2005   3.448434
54  2003   3.444777
47  1996   3.426600
48  1997   3.415764
51  2000   3.356104

[62 rows x 2 columns]>

## Ответ: утверждение не верно.